// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ZkDCz5Wf6YEMESYIKsHE21xXY0JFvuA',
    appId: '1:493513065809:web:16088f19ef63c1d314ff70',
    messagingSenderId: '493513065809',
    projectId: 'cardapio-ebdd6',
    authDomain: 'cardapio-ebdd6.firebaseapp.com',
    storageBucket: 'cardapio-ebdd6.firebasestorage.app',
    measurementId: 'G-L1F9D3HWLG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuBxvSHpL1l6uz8dEuvzkaKIRxKuEibUI',
    appId: '1:493513065809:ios:10cf644d3d72f84e14ff70',
    messagingSenderId: '493513065809',
    projectId: 'cardapio-ebdd6',
    storageBucket: 'cardapio-ebdd6.firebasestorage.app',
    iosBundleId: 'com.example.appProjetoCardapio',
  );
}
